export const Type ={
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',
    SET_USER:"SET_USER",
    // UPDATE_BASKET: 'UPDATE_BASKET',
    EMPTY_BASKET: 'EMPTY_BASKET',
    // SET_CURRENCY: 'SET_CURRENCY',
    // SET_SORT_BY: 'SET_SORT_BY',
}